### ISSUE TITLE
Pipeline to build external releases

### ISSUE THREAD

**Issue by bikramnehra** [SUSE/kubecf#171]
Currently there are two pipelines

- **Release images cf-deployment** -> for building images in cf-deployment releases
- **Buildpacks build pipelines** -> for building suse buildpack releases

The intent to this task is to have a new pipeline which covers all releases external to `cf-deployment` and `buildpacks`. The pipeline must provide a mechanism for adding, updating and building new releases and versions e.g:

```
releases:
- name: cf-mysql-release
  url: ~
  versions:
  - 1.0.0
  - 1.1.0
  - 1.2.0
- name: capi-release
  url: ~
  versions:
  - 1.83.0
  - 1.84.0
- name: cf-acceptance-tests-release
  url: ~
  versions:
  - 0.0.5
  - 0.0.6
```
