### ISSUE TITLE
Make the errand tests default to disabled (not smoke)

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#234]
**Describe the bug**

Currently, CATS and brain are enabled by default. We should deploy them only when set on `values.yaml`.

In environments that don't need to run those, the overhead of downloading the images is big.
On the security side, brain-tests need a cluster-admin role that we should not create by default.

A good approach would be to have `testing` key on `values.yaml`:

```yaml
testing:
  smoke-tests:
    enabled: true
  acceptance-tests:
    enabled: false
  brain-tests:
    enabled: false
  sync-integration-tests:
    enabled: false
```

**To Reproduce**

Deploy kubecf and check that all the errands are present in the final manifest by default.

**Expected behavior**

By default, they should not be present in the final manifest.

**Additional context**

In production environments, only smoke-tests make sense.
